name = "shandong-worker"
main = "server/worker.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "npm run build"
upload_dir = "dist/client"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
# Add other environment variables here if needed
