name = "shandong-worker"
main = "server/worker.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "npm run build"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
MONGODB_URI = "mongodb+srv://maibauntourph_db_user:Admin1234@kennethempire.obmfscv.mongodb.net/outcatering?retryWrites=true&w=majority&appName=kennethempire"
GEMINI_API_KEY = "AIzaSyB9bSw4CQ5aw-enPR10IjtpuVLqxYaTHlo"
JWT_SECRET = "shandong-premium-secret-keep-secure"
